spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.143.217.76:5040/testdb?useUnicode=true&characterEncoding=utf8&currentSchema=public&stringtype=unspecified
    username: test_seecooker
    password: testseecooker

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: postgresql
  data:
    redis:
      host: 43.143.217.76
      port: 6379
      password: seecooker
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
server:
  port: 8080