server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://124.222.18.205:9932/seecooker?useUnicode=true&characterEncoding=utf8&currentSchema=public&stringtype=unspecified
    username: se2dbuser
    password: se2dbpasswd

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: postgresql